[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "testpkg"
authors = [{name = "Juan Luis Cano Rodríguez", email = "hello@juanlu.space"}]
dynamic = ["version", "description"]
